src/Entity/Bill.php
<?php

namespace App\Entity;

use App\Repository\BillRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BillRepository::class)
 */
class Bill
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity=BillDetail::class)
     */
    private $BillDetail;

    /**
     * @ORM\ManyToOne(targetEntity=Customer::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Customer;

    /**
     * @ORM\ManyToOne(targetEntity=Staff::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Staff;

    /**
     * @ORM\Column(type="float")
     */
    private $Discount;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    public function __construct()
    {
        $this->BillDetail = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, BillDetail>
     */
    public function getBillDetail(): Collection
    {
        return $this->BillDetail;
    }

    public function addBillDetail(BillDetail $billDetail): self
    {
        if (!$this->BillDetail->contains($billDetail)) {
            $this->BillDetail[] = $billDetail;
        }

        return $this;
    }

    public function removeBillDetail(BillDetail $billDetail): self
    {
        $this->BillDetail->removeElement($billDetail);

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->Customer;
    }

    public function setCustomer(?Customer $Customer): self
    {
        $this->Customer = $Customer;

        return $this;
    }

    public function getStaff(): ?Staff
    {
        return $this->Staff;
    }

    public function setStaff(?Staff $Staff): self
    {
        $this->Staff = $Staff;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->Discount;
    }

    public function setDiscount(float $Discount): self
    {
        $this->Discount = $Discount;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Form/BillType.php
<?php

namespace App\Form;

use App\Entity\Bill;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BillType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Discount')
            ->add('Date')
            ->add('BillDetail')
            ->add('Customer')
            ->add('Staff')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Bill::class,
        ]);
    }
}

src/Controller/BillController.php
<?php

namespace App\Controller;

use App\Entity\Bill;
use App\Form\BillType;
use App\Repository\BillRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bill")
 */
class BillController extends AbstractController
{
    /**
     * @Route("/", name="app_bill_index", methods={"GET"})
     */
    public function index(BillRepository $billRepository): Response
    {
        return $this->render('bill/index.html.twig', [
            'bills' => $billRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_bill_new", methods={"GET", "POST"})
     */
    public function new(Request $request, BillRepository $billRepository): Response
    {
        $bill = new Bill();
        $form = $this->createForm(BillType::class, $bill);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $billRepository->add($bill, true);

            return $this->redirectToRoute('app_bill_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bill/new.html.twig', [
            'bill' => $bill,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_bill_show", methods={"GET"})
     */
    public function show(Bill $bill): Response
    {
        return $this->render('bill/show.html.twig', [
            'bill' => $bill,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_bill_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Bill $bill, BillRepository $billRepository): Response
    {
        $form = $this->createForm(BillType::class, $bill);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $billRepository->add($bill, true);

            return $this->redirectToRoute('app_bill_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bill/edit.html.twig', [
            'bill' => $bill,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_bill_delete", methods={"POST"})
     */
    public function delete(Request $request, Bill $bill, BillRepository $billRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bill->getId(), $request->request->get('_token'))) {
            $billRepository->remove($bill, true);
        }

        return $this->redirectToRoute('app_bill_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/bill/_delete_form.html.twig
<form method="post" action="{{ path('app_bill_delete', {'id': bill.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bill.id) }}">
    <button class="btn">Delete</button>
</form>

templates/bill/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bill/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bill{% endblock %}

{% block body %}
    <h1>Edit Bill</h1>

    {{ include('bill/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_bill_index') }}">Back to list</a>

    {{ include('bill/_delete_form.html.twig') }}
{% endblock %}

templates/bill/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bill list{% endblock %}

{% block body %}
    <h1>Bill list</h1>
    <a href="{{ path('app_bill_new') }}">Create new</a>
    <table id="product" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Discount</th>
                <th>Customer</th>
                <th>Staff</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bill in bills %}
            <tr>
                <td>{{ bill.id }}</td>
                <td>{{ bill.Discount }}</td>
                <td>{{ bill.customer.FirstName}}</td>
                <td>{{ bill.staff.FirstName}}</td>
                <td>{{ bill.Date ? bill.Date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_bill_show', {'id': bill.id}) }}">Show</a>
                    <a href="{{ path('app_bill_edit', {'id': bill.id}) }}">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/bill/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bill{% endblock %}

{% block body %}
    <h1>Create new Bill</h1>

    {{ include('bill/_form.html.twig') }}

    <a href="{{ path('app_bill_index') }}">back to list</a>
{% endblock %}

templates/bill/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bill{% endblock %}

{% block body %}
    <h1>Bill</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ bill.id }}</td>
            </tr>
            <tr>
                <th>Discount</th>
                <td>{{ bill.Discount }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ bill.Date ? bill.Date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_bill_index') }}">back to list</a>

    <a href="{{ path('app_bill_edit', {'id': bill.id}) }}">edit</a>

    {{ include('bill/_delete_form.html.twig') }}
{% endblock %}